apiVersion: v1
kind: Secret
metadata:
  name: registry-redhat-credentials
type: Opaque
stringData:
  registry-redhat-username: "${REGISTRY_REDHAT_USERNAME}"
  registry-redhat-password: "${REGISTRY_REDHAT_PASSWORD}"
