apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: authenticate-central
spec:
  params:
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: ocm-token
      type: string
      description: Token generated when logging into OCM using Service Account credentials
  results:
    - name: rox-api-token
      type: string
      description: OIDC Token for ACS authentication, obtained after exchanching the OCM token
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  volumes:
    - name: shell-scripts
      configMap:
        name: rhacs-shell-scripts
        defaultMode: 0755
    - name: python-scripts
      configMap:
        name: rhacs-python-scripts
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-roxctl
      command: ["/scripts/shell/install-roxctl.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: authenticate-central
      results:
        - name: rox-api-token
          type: string
          description: OIDC Token for ACS authentication, obtained after exchanching the OCM token
      command: ["python", "/scripts/python/authenticate-central.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(params.ocm-token)
        - name: ROX_ENDPOINT
          value: $(params.rox-endpoint)
        - name: STEP_RESULT_PATH
          value: $(step.results.rox-api-token.path)
        - name: TASK_RESULT_PATH
          value: $(results.rox-api-token.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: test-rox-api-token
      command: ["/scripts/shell/test-rox-api-token.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      env:
        - name: ROX_API_TOKEN
          value: $(steps.authenticate-central.results.rox-api-token)
        - name: ROX_ENDPOINT
          value: $(params.rox-endpoint)
      workingDir: $(workspaces.binaries.path)
  workspaces:
    - description: |
        Binaries
      name: binaries
