apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: configure-central
spec:
  params:
    - name: registry-redhat-creds-secret
      type: string
      description: Name of Secret containing credentials for registry.redhat.com
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: rox-api-token
      type: string
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: configure-central
      results:
        - name: rox-api-token
          type: string
      command:
        - python
        - /scripts/configure-central.py
      volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      env:
        - name: ROX_ENDPOINT
          value: $(params.rox-endpoint)
        - name: ROX_API_TOKEN
          value: $(params.rox-api-token)
        - name: REGISTRY_REDHAT_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.registry-redhat-creds-secret)
              key: "registry-redhat-username"
        - name: REGISTRY_REDHAT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.registry-redhat-creds-secret)
              key: "registry-redhat-password"
  volumes:
    - name: scripts
      configMap:
        name: configure-central-scripts
        defaultMode: 0755
