apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: configure-central
spec:
  params:
    - name: registry-redhat-creds-secret
      type: string
      description: Name of Secret containing credentials for registry.redhat.com
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: rox-api-token
      type: string
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: configure-central
      results:
        - name: rox-api-token
          type: string
      script: |
        #!/bin/env python
        import os
        import requests

        ROX_ENDPOINT = os.getenv("ROX_ENDPOINT")
        headers = {"Authorization": "Bearer " + os.getenv("ROX_API_TOKEN")}
        payload = {
          "id": "",
          "name": "registry.redhat.io",
          "type": "rhel",
          "categories": [
            "REGISTRY"
          ],
          "docker": {
            "endpoint": "registry.redhat.io",
            "username": os.getenv("REGISTRY_REDHAT_USERNAME"),
            "password": os.getenv("REGISTRY_REDHAT_PASSWORD"),
            "insecure": False
          },
          "autogenerated": False,
          "clusterId": "",
          "skipTestIntegration": False,
          "source": None
        }

        response = requests.post(f"{ROX_ENDPOINT}/v1/imageintegrations", headers=headers, json=payload)
        return_code = response.status_code

        if return_code != 200:
          print("Failed to add image integration for registry.redhat.io")
          print(response.text)
          response.raise_for_status()

        print("Added image integration for registry.redhat.io")
      env:
        - name: ROX_ENDPOINT
          value: $(params.rox-endpoint)
        - name: ROX_API_TOKEN
          value: $(params.rox-api-token)
        - name: REGISTRY_REDHAT_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.registry-redhat-creds-secret)
              key: "registry-redhat-username"
        - name: REGISTRY_REDHAT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.registry-redhat-creds-secret)
              key: "registry-redhat-password"
