apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: destroy-central
spec:
  params:
    - name: central-id
      type: string
      description: ID of provisionned central in ACS
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  volumes:
    - name: shell-scripts
      configMap:
        name: rhacs-shell-scripts
        defaultMode: 0755
    - name: python-scripts
      configMap:
        name: rhacs-python-scripts
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-ocm
      command: ["/scripts/shell/install-ocm.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      workingDir: $(workspaces.binaries.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: ocm-login
      results:
        - name: ocm-token
          type: string
          description: OCM Token
      command: ["/scripts/shell/ocm-token.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      env:
        - name: STEP_RESULT_PATH
          value: $(step.results.ocm-token.path)
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-id"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-secret"
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: destroy-central
      command: ["python", "/scripts/python/destroy-central.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
    - image: image-registry.openshift-image-registry.svc:5000/lslavkov-testing/python3-with-requests:latest
      name: wait-for-central-delete
      command: ["python", "/scripts/python/wait-for-central-delete.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
  workspaces:
    - description: |
        Binaries
      name: binaries
