apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: destroy-central
spec:
  params:
    - name: central-id
      type: string
      description: ID of provisionned central in ACS
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-ocm
      command:
        - /scripts/install-ocm.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      workingDir: $(workspaces.binaries.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: ocm-login
      results:
        - name: ocm-token
          type: string
          description: OCM Token
      command:
        - /scripts/ocm-login.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-id"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-secret"
        - name: STEP_RESULTS_OCM_TOKEN_PATH
          value: $(step.results.ocm-token.path)
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: destroy-central
      command:
        - python
        - /scripts/destroy-central.py
      volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: wait-for-central-delete
      command:
        - python
        - /scripts/wait-for-central-delete.py
      volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
  volumes:
    - name: scripts
      configMap:
        name: destroy-central-scripts
        defaultMode: 0755
  workspaces:
    - description: |
        Binaries
      name: binaries
