apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: destroy-central
spec:
  params:
    - name: central-id
      type: string
      description: ID of provisionned central in ACS
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-ocm
      script: |
        #!/bin/sh
        # arch="$(uname -m | sed "s/x86_64//")"; arch="${arch:+-$arch}"
        curl -L -f -o ocm  https://github.com/openshift-online/ocm-cli/releases/download/v1.0.14/ocm-linux-amd64
        chmod +x ocm
        ./ocm version
      workingDir: $(workspaces.binaries.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: ocm-login
      results:
        - name: ocm-token
          type: string
          description: OCM Token
      script: |
        #!/bin/sh
        ./ocm login --client-id ${CLIENT_ID} --client-secret ${CLIENT_SECRET}
        printf '%s' "$(./ocm token)" > $(step.results.ocm-token.path)
      env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-id"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: rh-openid-credentials
              key: "client-secret"
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: destroy-central
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
      script: |
        #!/bin/env python
        import os
        import requests

        ocm_token = os.getenv("OCM_TOKEN")
        central_id = os.getenv("CENTRAL_ID")

        API_URL = f"https://api.openshift.com/api/rhacs/v1/centrals/{central_id}?async=true"
        headers = {"Authorization": "Bearer " + ocm_token, "Content-Type": "application/json"}

        print(f"Sending Central deletion request with id {central_id}")

        response = requests.delete(API_URL, headers=headers)

        if response.status_code != 200:
          print(f"Return code: {response.status_code}")
          response.raise_for_status()

        print("Central deletion request successfully sent")
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: wait-for-central-delete
      script: |
        #!/bin/env python
        import os
        import time
        import requests

        ocm_token = os.getenv("OCM_TOKEN")
        central_id = os.getenv("CENTRAL_ID")

        headers = {"Authorization": "Bearer " + ocm_token, "Content-Type": "application/json"}
        return_code = None

        while return_code != 404:
          print("Querying central status")
          response = requests.get(
              f"https://api.openshift.com/api/rhacs/v1/centrals/{central_id}",
              headers=headers,
          )
          central_request = response.json()
          print(central_request)
          central_status = central_request.get("status")
          return_code = response.status_code

          if return_code != 404:
            print(f"Central has status '{central_status}', retrying in 10 seconds...")
            time.sleep(10)

        print("Central is deleted")
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(params.central-id)
  workspaces:
    - description: |
        Binaries
      name: binaries
