apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: provision-central
spec:
  params:
    - name: service-account-creds-secret
      type: string
      description: Name of Secret containing Service Account credentials
    - name: cloud-account-id
      type: string
      description: AWS ID used for Central provisioning via ACS CS
    - name: central-aws-region
      type: string
      description: AWS Region where to provision Central
    - name: existing-central-id
      type: string
      description: Existing Central ID to reuse instead of creating a new one
      default: ""
    - name: pipelinerun-uid
      type: string
      description: Unique pipelineRun identifier, used to craft a unique Central name.
  results:
    - name: central-id
      type: string
      description: ID of provisionned central in ACS CS
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: ocm-token
      type: string
      description: Token generated when logging into OCM using Service Account credentials
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  volumes:
    - name: shell-scripts
      configMap:
        name: rhacs-shell-scripts
        defaultMode: 0755
    - name: python-scripts
      configMap:
        name: rhacs-python-scripts
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-ocm
      command: ["/scripts/shell/install-ocm.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      workingDir: $(workspaces.binaries.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: ocm-login
      results:
        - name: ocm-token
          type: string
          description: Token generated when logging into OCM using Service Account credentials
      command: ["/scripts/shell/ocm-token.sh"]
      volumeMounts:
        - name: shell-scripts
          mountPath: /scripts/shell
          readOnly: true
      env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: $(params.service-account-creds-secret)
              key: "client-id"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: $(params.service-account-creds-secret)
              key: "client-secret"
        - name: STEP_RESULT_PATH
          value: $(step.results.ocm-token.path)
        - name: TASK_RESULT_PATH
          value: $(results.ocm-token.path)
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/lslavkov-testing/python3-with-requests:latest
      name: provision-central
      results:
        - name: central-id
          type: string
          description: ID of provisionned central in ACS CS
      command: ["python", "/scripts/python/provision-central.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: PIPELINERUN_UID
          value: $(params.pipelinerun-uid)
        - name: CLOUD_ACCOUNT_ID
          value: $(params.cloud-account-id)
        - name: CENTRAL_AWS_REGION
          value: $(params.central-aws-region)
        - name: EXISTING_CENTRAL_ID
          value: $(params.existing-central-id)
        - name: STEP_RESULT_PATH
          value: $(step.results.central-id.path)
        - name: TASK_RESULT_PATH
          value: $(results.central-id.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: wait-for-central-ready
      command: ["python", "/scripts/python/wait-for-central-ready.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(steps.provision-central.results.central-id)
        - name: ROX_ENDPOINT_PATH
          value: $(results.rox-endpoint.path)
  workspaces:
    - description: |
        Binaries
      name: binaries
