apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: provision-central
spec:
  params:
    - name: service-account-creds-secret
      type: string
      description: Name of Secret containing Service Account credentials
    - name: cloud-account-id
      type: string
      description: AWS ID used for Central provisioning via ACS CS
    - name: central-aws-region
      type: string
      description: AWS Region where to provision Central
    - name: pipelinerun-uid
      type: string
      description: Unique pipelineRun identifier, used to craft a unique Central name.
  results:
    - name: central-id
      type: string
      description: ID of provisionned central in ACS CS
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: ocm-token
      type: string
      description: Token generated when logging into OCM using Service Account credentials
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: install-ocm
      script: |
        #!/bin/sh
        # arch="$(uname -m | sed "s/x86_64//")"; arch="${arch:+-$arch}"
        curl -L -f -o ocm  https://github.com/openshift-online/ocm-cli/releases/download/v1.0.14/ocm-linux-amd64
        chmod +x ocm
        ./ocm version
      workingDir: $(workspaces.binaries.path)
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: ocm-login
      results:
        - name: ocm-token
          type: string
          description: Token generated when logging into OCM using Service Account credentials
      script: |
        #!/bin/sh
        ./ocm login --client-id ${CLIENT_ID} --client-secret ${CLIENT_SECRET}
        printf '%s' "$(./ocm token)" > $(step.results.ocm-token.path)
        printf '%s' "$(./ocm token)" > $(results.ocm-token.path)
      env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: $(params.service-account-creds-secret)
              key: "client-id"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: $(params.service-account-creds-secret)
              key: "client-secret"
      workingDir: $(workspaces.binaries.path)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: provision-central
      results:
        - name: central-id
          type: string
          description: ID of provisionned central in ACS CS
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: PIPELINERUN_UID
          value: $(params.pipelinerun-uid)
        - name: CLOUD_ACCOUNT_ID
          value: $(params.cloud-account-id)
        - name: CENTRAL_AWS_REGION
          value: $(params.central-aws-region)
      script: |
        #!/bin/env python
        import os
        import requests

        API_URL = "https://api.openshift.com/api/rhacs/v1/centrals?async=true"
        central_name_suffix = os.getenv("PIPELINERUN_UID").split("-")[0]
        central_name = f"vuln-scan-cert-{central_name_suffix}"

        headers = {"Authorization": "Bearer " + os.getenv("OCM_TOKEN"), "Content-Type": "application/json"}
        payload = {
          'name': central_name,
          'cloud_provider': 'aws',
          'multi_az': True,
          'region': os.getenv("CENTRAL_AWS_REGION"),
          'cloud_account_id': os.getenv("CLOUD_ACCOUNT_ID"),
        }

        print(f"Sending Central creation request with name {central_name}")

        response = requests.post(
          API_URL,
          json=payload,
          headers=headers,
        )

        if response.status_code != 200:
          print(f"Return code: {response.status_code}")
          print(response.json())
          response.raise_for_status()

        central_request = response.json()
        central_id = central_request.get("id")
        print("Central creation request successfully sent")
        print(f"Central ID: {central_id}")
        with open('$(step.results.central-id.path)', 'w') as f:
          f.write(central_id)
        with open('$(results.central-id.path)', 'w') as f:
          f.write(central_id)
    - image: image-registry.openshift-image-registry.svc:5000/default/python3-with-requests:latest
      name: wait-for-central-ready
      script: |
        #!/bin/env python
        import os
        import time
        import requests
        headers = {"Authorization": "Bearer " + os.getenv("OCM_TOKEN"), "Content-Type": "application/json"}
        central_request_status = None

        while central_request_status != "ready":
          print("Querying central status")
          response = requests.get(f"https://api.openshift.com/api/rhacs/v1/centrals/{os.getenv("CENTRAL_ID")}", headers=headers)
          central_request = response.json()
          print(central_request)
          central_request_status = central_request.get("status")

          if central_request_status != "ready":
            print("Central is not ready yet, retrying in 10 seconds...")
            time.sleep(10)

        print("Central is Ready")

        with open('$(results.rox-endpoint.path)', 'w') as f:
          f.write(central_request.get("centralUIURL"))
      env:
        - name: OCM_TOKEN
          value: $(steps.ocm-login.results.ocm-token)
        - name: CENTRAL_ID
          value: $(steps.provision-central.results.central-id)
  workspaces:
    - description: |
        Binaries
      name: binaries
