apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wait-for-scanner-init
spec:
  params:
    - name: rox-endpoint
      type: string
      description: Central UI Endpoint
    - name: rox-api-token
      type: string
  stepTemplate:
    computeResources: {}
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  volumes:
    - name: python-scripts
      configMap:
        name: rhacs-python-scripts
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/lslavkov-testing/python3-with-requests:latest
      name: wait-for-scanner-init
      command: ["python", "/scripts/python/wait-for-scanner-init.py"]
      volumeMounts:
        - name: python-scripts
          mountPath: /scripts/python
          readOnly: true
      env:
        - name: ROX_ENDPOINT
          value: $(params.rox-endpoint)
        - name: ROX_API_TOKEN
          value: $(params.rox-api-token)
