apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhacs
  namespace: default
spec:
  tasks:
    - name: provision-central
      taskRef:
        kind: Task
        name: provision-central
      params:
        - name: cloud-account-id
          value: $(params.cloud-account-id)
        - name: pipelinerun-uid
          value: $(context.pipelineRun.uid)
      workspaces:
        - name: binaries
          workspace: bin
    - name: authenticate-central
      taskRef:
        kind: Task
        name: authenticate-central
      params:
        - name: central-id
          value: $(tasks.provision-central.results.central-id)
        - name: ocm-token
          value: $(tasks.provision-central.results.ocm-token)
        - name: rox-endpoint
          value: $(tasks.provision-central.results.rox-endpoint)
      workspaces:
        - name: binaries
          workspace: bin
    - name: wait-for-scanner-init
      taskRef:
        kind: Task
        name: wait-for-scanner-init
      params:
        - name: rox-endpoint
          value: $(tasks.provision-central.results.rox-endpoint)
        - name: rox-api-token
          value: $(tasks.authenticate-central.results.rox-api-token)

    # - name: run-image-scan
    # - name: upload-result
  params:
    - name: image
      type: string
      description: Image to scan - currently unused
      default: alpine
    - name: cloud-account-id
      type: string
      description: AWS ID used for Central provisioning via ACS
  finally:
    - name: destroy-central
      taskRef:
        kind: Task
        name: destroy-central
      params:
        - name: central-id
          value: $(tasks.provision-central.results.central-id)
      workspaces:
        - name: binaries
          workspace: bin
  workspaces:
    - name: bin
