import os
from contextlib import suppress

import requests

ROX_ENDPOINT = os.getenv("ROX_ENDPOINT")
headers = {"Authorization": f"Bearer {os.getenv('ROX_API_TOKEN')}"}
payload = {
    "id": "",
    "name": "registry.redhat.io",
    "type": "rhel",
    "categories": ["REGISTRY"],
    "docker": {
        "endpoint": "registry.redhat.io",
        "username": os.getenv("REGISTRY_REDHAT_USERNAME"),
        "password": os.getenv("REGISTRY_REDHAT_PASSWORD"),
        "insecure": False,
    },
    "autogenerated": False,
    "clusterId": "",
    "skipTestIntegration": False,
    "source": None,
}

response = requests.post(f"{ROX_ENDPOINT}/v1/imageintegrations", headers=headers, json=payload)
return_code = response.status_code

message = None
with suppress(requests.exceptions.JSONDecodeError, AttributeError):
    message = response.json().get("message")

if return_code != 200:
    if message and "already exists" in message:
        print("Central already configured")
    else:
        print("Failed to add image integration for registry.redhat.io")
        print(response.text)
        response.raise_for_status()
else:
    print("Added image integration for registry.redhat.io")
